version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  checkout:
    steps:
      - checkout
  build:
    executor: node/default
    steps:
      - node/install-packages
      - run:
          name: "Build"
          command: npm run build
      - store_artifacts:
          path: ./dist
          destination: artifacts

workflows:
  install-build-workflow:
    jobs:
      - build
