version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Build"
          command: npm run build
      - store_artifacts:
          path: ./dist
          destination: artifacts

workflows:
  build-workflow:
    jobs:
      - build
