version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install
          environment:
            HOME: .
      - run:
          name: "Build"
          command: npm run build
      - store_artifacts:
          path: ./dist
          destination: artifacts
      - persist_to_workspace:
          root: ~/
          paths: 
            - project/dist
  deploy-to-s3:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - run:
          command: |
            echo 'export RELEASE_VERSION=`echo ${CIRCLE_TAG} | cut -d '/' -f 2`' >> "$BASH_ENV"
            source $BASH_ENV
      - checkout
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          arguments: --acl public-read
          from: ~/project/dist
          to: 's3://exalted-apps/exalted-api/${RELEASE_VERSION}'

workflows:
  install-build-workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /release\/.*/
      - deploy-to-s3:
          context:
            - exalted
          requires:
            - build
          filters:
            tags:
              only: /release\/.*/
            branches:
              ignore: /.*/
