version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  install-deps:
    - checkout
    - node/install-packages:
        pkg-manager: npm
        environment:
          HOME: .
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: "Build"
          command: npm run build
      - store_artifacts:
          path: ./dist
          destination: artifacts

workflows:
  install-build-workflow:
    jobs:
      - install-deps
      - build:
          requires: 
            - install-deps
