version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  install-deps:
    executor: node/default
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: "Install Dependecies"
          command: npm install

workflows:
  intall-deps-workflow:
    jobs:
      - install-deps
