version: 2.1
orbs:
  node: circleci/node@5.0.2
  asw-s3: circleci/aws-s3@3.0.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install
          environment:
            HOME: .
      - run:
          name: "Build"
          command: npm run build
      - store_artifacts:
          path: ./dist
          destination: artifacts
      - persist_to_workspace:
          root: ~/
          paths: 
            - project/dist
            - project/node_modules
  deploy-to-s3:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          arguments: --acl public-read
          from: project/dist
          to: 's3://exalted-apps/{CLI_TAGS}/exalted-api'

workflows:
  install-build-workflow:
    jobs:
      - build
      - deploy-to-s3:
          context:
            - exalted
          requires:
            - build
          filters:
            tags:
              only: /release\/.*/
            branches:
              ignore: /.*/
