version: 2.1
jobs:
  install-deps:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Install Dependecies"
          command: npm install

workflows:
  intall-deps-workflow:
    jobs:
      - install-deps
