version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          command: npm install
          environment:
            HOME: .
      - run:
          name: "Build"
          command: npm run build
      - store_artifacts:
          path: ./dist
          destination: artifacts
      - persist_to_workspace:
          root: ~/
          paths: 
            - project/dist
            - project/node_modules
  test:
    executor: node/default
    steps:
      - run:
          command: ls node_modules

workflows:
  install-build-workflow:
    jobs:
      - build
