version: 2.1
jobs:
  install-deps:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Install Dependecies"
          command: npm install
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
        name: "Run build script"
        command: npm run build
      - store_artifacts:
          path: ./dist
          destination: artifacts
          
workflows:
  intall-and-build-workflow:
    jobs:
      - install-deps
      - build:
          requires:
            - install-deps
